# -- Site Configuration --
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/getting-started/

theme: "blowfish"
baseURL: "https://rewse.jp/blog/"
defaultContentLanguage: "ja"
disableLanguages: [] # to allow translation work requiring shipping to production

# pluralizeListTitles: true # hugo function useful for non-english languages

enableRobotsTXT: true
summaryLength: 0
hasCJKLanguage: true

buildDrafts: false
buildFuture: false

enableEmoji: true

googleAnalytics: "G-TPRYLTLRFG"

pagination:
  pagerSize: 15

imaging:
  anchor: "Center"

taxonomies:
  tag: "tags"
  category: "categories"

sitemap:
  changefreq: "always"
  filename: "sitemap.xml"
  priority: 0.5

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"

related:
  threshold: 0
  toLower: false
  indices:
    - name: "tags"
      weight: 100
    - name: "categories"
      weight: 100
    - name: "series"
      weight: 50
    - name: "authors"
      weight: 20
    - name: "date"
      weight: 10
    - applyFilter: false
      name: "fragmentrefs"
      type: "fragments"
      weight: 10
