# -- Markup --
# These settings are required for the theme to function.

goldmark:
  parser:
    wrapStandAloneImageWithinParagraph: false
    attribute:
      block: true
  renderer:
    unsafe: true
  extensions:
    passthrough:
      enable: true
      delimiters:
        block:
          - ['\[', '\]']
          - ['$$', '$$']
        inline:
          - ['\(', '\)']

highlight:
  noClasses: false

tableOfContents:
  startLevel: 2
  endLevel: 4
